# imagen docker a utilizar, en este caso usamos un sistema base alpine limpio
FROM alpine:3.12

# el gestor de paquetes alpine es apk, instala python y pip
RUN apk add python3-dev py-pip

# crea un directorio
WORKDIR /app

# copiamos nuestros archivos hacia la ruta dentro del contenedor
COPY src /app
COPY static /app/static
COPY templates /app/templates

# usando pip instalamos las dependencias requeridas para correr la aplicación
RUN pip install flask==1.1.2

# cuando corramos la imagen, ejecutará automaticamente la aplicación
CMD ["python3", "/app/app.py"]

